spring:
  cloud:
    config:
      server:
        git:
          uri: https://github.com/Willem520/cloud-config-repo.git
          username:
          password:
          search-paths: config-repo
      label: master

eureka:
  client:
    service-url: defaultZone=http://localhost:9050/eureka/