#配置文件dev|prod
spring:
  profiles:
    active: dev
  application:
    name: cloud-stream

#tomcat的URI编码
server:
  tomcat:
    uri-encoding: UTF-8
  port: 8280

#logback配置信息
logging:
  config: classpath:dev/logback-spring.xml
  path: /data/logs/cloud/cloud-stream