#配置文件dev|prod
spring:
  profiles:
    active: @profileActive@

#tomcat的URI编码
server:
  tomcat:
    uri-encoding: UTF-8

endpoints:
  shutdown:
    enabled: true #启用shutdown
    sensitive: false #shutdown安全验证

#路由设置
zuul:
  prefix: /micro/api
  routes:
    micro:
      path: /micro/**
      serviceId: cloud-feign
      stripPrefix: false

#logback配置信息
logging:
  config: classpath:@profileActive@/logback-spring.xml
  path: /data/logs/cloud/cloud-zuul